substitutions:
  friendly_name: "E-Ink Display"
  device_name: "esp32-eink"

esphome:
  name: $device_name

esp32:
  board: nodemcu-32s

wifi:
  power_save_mode: high
  output_power: 15
  fast_connect: true
  networks:
#  - ssid: !secret wifi_ssid_1
#    password: !secret wifi_password_1
#  - ssid: !secret wifi_ssid_2
#    password: !secret wifi_password_2
#  - ssid: !secret wifi_ssid_3
#    password: !secret wifi_password_3
#  - ssid: !secret wifi_ssid_4
#    password: !secret wifi_password_4
  - ssid: !secret wifi_ssid_5
    password: !secret wifi_password_5


ota:
  - platform: esphome
    password: !secret ota_password

logger:
  level: DEBUG

api:
  encryption:
    key: !secret esp32-eink-key
  reboot_timeout: 24h

web_server:
  port: 80

 

external_components:
  - source: github://dmamontov/esphome-blekeyboard
  

ble_keyboard:
  id: my_ble_keyboard
  name: "Blutzucker Tastatur"
  manufacturer_id: "MamonTech"
  battery_level: 100
  reconnect: true
  buttons: true
  use_default_libs: false
  
  
  
button:
  - platform: template
    name: "Screenshot"
    id: screenshot
    on_press:
      then:
        - ble_keyboard.combination:
            id: my_ble_keyboard
            delay: 20
            keys:
              - 0x83 # KEY_LEFT_GUIs
              - 0x85
              - "3"
#        - ble_keyboard.print:
#            id: my_ble_keyboard
#            text: "3"
              
  - platform: template
    name: "Spotlight"
    id: spotlight
    on_press:
      then:
        - ble_keyboard.combination:
            id: my_ble_keyboard
            delay: 20
            keys:
              - 0x83 # KEY_LEFT_GUI
              - " "

