substitutions:
  friendly_name: "E-Ink Display"
  device_name: "esp32-eink"

esphome:
  name: $device_name

esp32:
  board: nodemcu-32s

wifi:
  networks:
  - ssid: !secret wifi_ssid_1
    password: !secret wifi_password_1
  - ssid: !secret wifi_ssid_2
    password: !secret wifi_password_2
  - ssid: !secret wifi_ssid_3
    password: !secret wifi_password_3
  - ssid: !secret wifi_ssid_4
    password: !secret wifi_password_4
  - ssid: !secret wifi_ssid_5
    password: !secret wifi_password_5


ota:
  - platform: esphome
    password: !secret ota_password

logger:
  level: DEBUG

api:
  encryption:
    key: !secret esp32-eink-key
  reboot_timeout: 24h

web_server:
  port: 80

font:
  - file: 'fonts/OpenSans-Bold.ttf'
    id: openSansBold_font
    size: 20
    glyphs:
      ['&', '@', '!', '?', ',', '.', '"', '%', '(', ')', '+', '-', '_', ':', '°', '0',
       '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E',
       'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S',
       'T', 'U', 'V', 'W', 'X', 'Y', 'Z', ' ', 'a', 'b', 'c', 'd', 'e', 'f',
       'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't',
       'u', 'v', 'w', 'x', 'y', 'z', 'å', 'ä', 'ö', 'ü', 'Ä', 'Ö', 'Ü', '/', '€', '’', 'ß']
 
  - file: 'fonts/OpenSans-Bold.ttf'
    id: watch_font
    size: 90
    glyphs:
      [':', ".", '0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Berlin
    servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
      - 2.pool.ntp.org

external_components:
  - source: github://pr#6209
    components: [ waveshare_epaper ]

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23

display:
  - platform: waveshare_epaper
    id: my_display
    cs_pin: GPIO26
    dc_pin: GPIO25
    reset_pin: GPIO33
    busy_pin: GPIO27
    model: 4.20in-v2
    # full_update_every: 30 # not available for 4.20 inch model
    update_interval: 180s
    reset_duration: 2ms
    rotation: 270
    lambda: |
     it.print(0, 0, id(openSansBold_font), "Anjas Nightscout Display :)");

     //Time
     it.strftime(10, 150, id(watch_font),TextAlign::BOTTOM_LEFT, "%H:%M", id(sntp_time).now());
     it.strftime(10, 160, id(openSansBold_font),TextAlign::BOTTOM_LEFT, "%d.%m.%y, KW %W", id(sntp_time).now());
