substitutions:
  friendly_name: ESP8266 Temp-1
  device_name: esp8266-temp-1

esphome:
  name: $device_name
  platform: ESP8266
  board: nodemcuv2

wifi:
  networks:
  - ssid: !secret wifi_ssid_1
    password: !secret wifi_password_1
  - ssid: !secret wifi_ssid_2
    password: !secret wifi_password_2

logger:
  level: INFO

api:
  encryption:
    key: !secret esp8266-temp-1-key 
  reboot_timeout: 24h

ota:
  password: !secret ota_password

web_server:
  port: 80

time:
  - platform: homeassistant
    id: homeassistant_time

dallas:
  - pin: GPIO5

sensor:
  - platform: dallas
    address: 0x3f000802de8fbd10 
    name: "$friendly_name Dallas"

  - platform: dht
    pin: GPIO4
    model: DHT11
    temperature:
      name: "$friendly_name DHT Temperature"
    humidity:
      name: "$friendly_name DHT Humidity"
    update_interval: 60s
