substitutions:
  friendly_name: "Plug ET28 1"
  device_name: "plug-et28-1"

esphome:
  name: $device_name

esp32:
  board: esp32-c3-devkitm-1

wifi:
  networks:
  - ssid: !secret wifi_ssid_1
    password: !secret wifi_password_1
  - ssid: !secret wifi_ssid_2
    password: !secret wifi_password_2
  - ssid: !secret wifi_ssid_3
    password: !secret wifi_password_3
  - ssid: !secret wifi_ssid_4
    password: !secret wifi_password_4


  ap:
    ssid: "$friendly_name AP"
    password: !secret wifi_password_1

ota:
  - platform: esphome
    password: !secret ota_password

logger:
  level: DEBUG

api:
  encryption:
    key: !secret plug-et28-1-key
  reboot_timeout: 24h

web_server:
  port: 80

esp32_ble_tracker:
  scan_parameters:
    active: false

bluetooth_proxy:
  active: true


status_led:
  pin:
    number: GPIO20
    inverted: false

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO05
      mode: INPUT_PULLUP
      inverted: True
    name: "$friendly_name Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "$friendly_name Status"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "$friendly_name IP Address"

sensor:
  - platform: hlw8012
    model: "BL0937"
    sel_pin: 
      number: GPIO04
      inverted: true
    cf_pin: GPIO03
    cf1_pin: GPIO07
    # 2624: 387 V
    # 2720: 401 V
    # 224: 33 V
    # ToDo: Calibrate using https://esphome.io/components/sensor/hlw8012.html
    voltage_divider: "1556"
    current_resistor: "0.001"
    current:
      name: "$friendly_name Current"
      filters:
        - multiply: "1.0"
    voltage:
      name: "$friendly_name Voltage"
    power:
      name: "$friendly_name Power"
    energy:
      name: "$friendly_name Energy"
    update_interval: 10s

  - platform: wifi_signal
    name: "$friendly_name WiFi Signal"
    update_interval: 30s

  - platform: internal_temperature
    name: "$friendly_name Internal Temperature"
    update_interval: 60s

  - platform: template
    icon: mdi:memory
    name: Free Memory
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL) / 1024;
    unit_of_measurement: 'kB'
    state_class: measurement
    entity_category: "diagnostic"

  - platform: uptime
    name: "$friendly_name Uptime"

switch:
  - platform: gpio
    name: "$friendly_name Relay"
    pin: GPIO06
    id: "relay"
