esphome:
  name: plug-et28-1 

esp32:
  board: esp32-c3-devkitm-1

wifi:
  networks:
  - ssid: !secret wifi_ssid_1
    password: !secret wifi_password_1
  - ssid: !secret wifi_ssid_2
    password: !secret wifi_password_2
  - ssid: !secret wifi_ssid_3
    password: !secret wifi_password_3
  - ssid: !secret wifi_ssid_4
    password: !secret wifi_password_4


ota:
  - platform: esphome
    password: !secret ota_password
