substitutions:
  friendly_name: "Sonoff S26 2"
  device_name: sonoff-s26-2

esphome:
  name: $device_name
 
esp8266:
  board: esp01_1m

 
wifi:
  min_auth_mode: "WPA2"
  networks:
  - ssid: !secret wifi_ssid_1
    password: !secret wifi_password_1
  - ssid: !secret wifi_ssid_2
    password: !secret wifi_password_2

status_led:
  pin:
    number: GPIO13
    inverted: false

logger:

api:
  encryption:
    key: !secret sonoff-s26-2-key

ota:
  - platform: esphome
    password: !secret ota_password

web_server:
  port: 80

time:
  - platform: homeassistant
    id: homeassistant_time

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff S26 2 Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "Sonoff S26 2 Status"

switch:
  - platform: gpio
    name: "Sonoff S26 2 Relay"
    pin: GPIO12
    id: "relay"
